
class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModeltrainerAftifact:...
class ModelEvaluationAtrifact:...
class ModelPusherAtrifact:...


